### ISSUE TITLE
Failure getting secret values from provider type secretsmanager: Failed to fetch secret from all regions

### ISSUE THREAD

**Issue by mafeifan** [aws/secrets-store-csi-driver-provider-aws#176] opened 2023-01-26 10:44 UTC
**Describe the bug**

k logs -n kube-system csi-secrets-store-provider-aws-nnjvn

```
I0126 07:28:50.650576       1 auth.go:123] Role ARN for default:govplt-deployment-sa is arn:aws-cn:iam::655418457877:role/KONE-EKS-govplt-secrets-readonly
E0126 07:28:50.892712       1 server.go:151] Failure getting secret values from provider type secretsmanager: Failed to fetch secret from all regions: /kone/govplt/elasticache/secret
I0126 07:30:53.184809       1 server.go:124] Servicing mount request for pod nginx-deployment-k8s-secrets-66d5f46844-v4w92 in namespace default using service account govplt-deployment-sa with region(s) cn-north-1
I0126 07:30:53.247115       1 auth.go:123] Role ARN for default:govplt-deployment-sa is arn:aws-cn:iam::655418457877:role/KONE-EKS-govplt-secrets-readonly
E0126 07:30:53.609110       1 server.go:151] Failure getting secret values from provider type secretsmanager: Failed to fetch secret from all regions: /kone/govplt/elasticache/secret
I0126 07:32:55.771473       1 server.go:124] Servicing mount request for pod nginx-deployment-k8s-secrets-66d5f46844-v4w92 in namespace default using service account govplt-deployment-sa with region(s) cn-north-1
I0126 07:32:55.777593       1 auth.go:123] Role ARN for default:govplt-deployment-sa is arn:aws-cn:iam::655418457877:role/KONE-EKS-govplt-secrets-readonly
E0126 07:32:56.183717       1 server.go:151] Failure getting secret values from provider type secretsmanager: Failed to fetch secret from all regions: /kone/govplt/elasticache/secret
```

k logs -n kube-system secrets-store-csi-driver-wwfxn

```
I0126 07:32:55.708010       1 server.go:151] "request" method="/csi.v1.Node/NodePublishVolume" req="{\"readonly\":true,\"target_path\":\"/var/lib/kubelet/pods/76bee6b4-1e9d-421b-a401-88c08c8f328f/volumes/kubernetes.io~csi/secrets-store-inline/mount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"csi.storage.k8s.io/ephemeral\":\"true\",\"csi.storage.k8s.io/pod.name\":\"nginx-deployment-k8s-secrets-66d5f46844-v4w92\",\"csi.storage.k8s.io/pod.namespace\":\"default\",\"csi.storage.k8s.io/pod.uid\":\"76bee6b4-1e9d-421b-a401-88c08c8f328f\",\"csi.storage.k8s.io/serviceAccount.name\":\"govplt-deployment-sa\",\"secretProviderClass\":\"nginx-deployment-spc-k8s-secrets\"},\"volume_id\":\"csi-9a2de871afbdd7628333c241e09fb619c5824541fffce76450288400e8fa5b8e\"}" deadline="1m59.997897253s"
I0126 07:32:55.708114       1 nodeserver.go:144] "node publish volume" target="/var/lib/kubelet/pods/76bee6b4-1e9d-421b-a401-88c08c8f328f/volumes/kubernetes.io~csi/secrets-store-inline/mount" volumeId="csi-9a2de871afbdd7628333c241e09fb619c5824541fffce76450288400e8fa5b8e" attributes=map[csi.storage.k8s.io/ephemeral:true csi.storage.k8s.io/pod.name:nginx-deployment-k8s-secrets-66d5f46844-v4w92 csi.storage.k8s.io/pod.namespace:default csi.storage.k8s.io/pod.uid:76bee6b4-1e9d-421b-a401-88c08c8f328f csi.storage.k8s.io/serviceAccount.name:govplt-deployment-sa secretProviderClass:nginx-deployment-spc-k8s-secrets] mount flags=[]
I0126 07:32:55.708169       1 mount_linux.go:219] Mounting cmd (mount) with arguments (-t tmpfs tmpfs /var/lib/kubelet/pods/76bee6b4-1e9d-421b-a401-88c08c8f328f/volumes/kubernetes.io~csi/secrets-store-inline/mount)
I0126 07:32:55.717713       1 nodeserver.go:359] "Using gRPC client" provider="aws" pod="nginx-deployment-k8s-secrets-66d5f46844-v4w92"
E0126 07:32:56.184444       1 nodeserver.go:242] "failed to mount secrets store object content" err="rpc error: code = Unknown desc = Failed to fetch secret from all regions: /kone/govplt/elasticache/secret" pod="default/nginx-deployment-k8s-secrets-66d5f46844-v4w92"
I0126 07:32:56.185002       1 nodeserver.go:88] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/76bee6b4-1e9d-421b-a401-88c08c8f328f/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="default/nginx-deployment-k8s-secrets-66d5f46844-v4w92"
I0126 07:32:56.185069       1 mount_linux.go:361] Unmounting /var/lib/kubelet/pods/76bee6b4-1e9d-421b-a401-88c08c8f328f/volumes/kubernetes.io~csi/secrets-store-inline/mount
I0126 07:32:56.193452       1 server.go:155] "response" method="/csi.v1.Node/NodePublishVolume" deadline="1m59.997897253s" duration="485.54268ms" status.code="Unknown" status.message="failed to mount secrets store objects for pod default/nginx-deployment-k8s-secrets-66d5f46844-v4w92, err: rpc error: code = Unknown desc = Failed to fetch secret from all regions: /kone/govplt/elasticache/secret"
```

**To Reproduce**

nginx-deployment-spc-k8s-secrets.yaml

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-spc-k8s-secrets
spec:
  provider: aws
  parameters:
    region: cn-north-1
    objects: |
      - objectName: "/kone/govplt/auroramysql/connectionstr"
        objectAlias: "db_conn_str"
        objectType: "ssmparameter"
      - objectName: "/kone/govplt/elasticache/secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: endpoints
            objectAlias: redis_endpoint
          - path: port
            objectAlias: redis_port

  secretObjects:
    - secretName: kone-govplt-secret # name of the Kubernetes Secret object
      type: Opaque # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
      labels:
        provider: "csi-driver"
      data:
        - objectName: redis_endpoint # name of the mounted content to sync. this could be the object name or the object alias
          key: redis_endpoint # data field to populate
        - objectName: redis_port
          key: redis_port
        - objectName: db_conn_str
          key: db_conn_str
```

nginx-deployment-k8s-secrets.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-k8s-secrets
  labels:
    app: nginx-k8s-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-k8s-secrets
  template:
    metadata:
      labels:
        app: nginx-k8s-secrets
    spec:
      serviceAccountName: govplt-deployment-sa
      containers:
      - name: nginx-deployment-k8s-secrets
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets"
            readOnly: true
        # I have turn on syncSecret.enable = true
        env:
          - name: DB_CONN_STR
            valueFrom:
              secretKeyRef:
                name: kone-govplt-secret
                key: db_conn_str
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: kone-govplt-secret
                key: redis_port

          - name: REDIS_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: kone-govplt-secret
                key: redis_endpoint

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: nginx-deployment-spc-k8s-secrets
```

aws-provider-installer.yml

```yaml
# https://kubernetes.io/docs/reference/access-authn-authz/rbac
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-aws
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-secrets-store-provider-aws-cluster-role
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-secrets-store-provider-aws-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-secrets-store-provider-aws-cluster-role
subjects:
- kind: ServiceAccount
  name: csi-secrets-store-provider-aws
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: csi-secrets-store-provider-aws
  labels:
    app: csi-secrets-store-provider-aws
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-secrets-store-provider-aws
  template:
    metadata:
      labels:
        app: csi-secrets-store-provider-aws
    spec:
      serviceAccountName: csi-secrets-store-provider-aws
      hostNetwork: false
      containers:
        - name: provider-aws-installer
          image: public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:1.0.r2-35-g41dc61e-2022.12.16.20.38
          imagePullPolicy: Always
          args:
              - --provider-volume=/etc/kubernetes/secrets-store-csi-providers
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: "/etc/kubernetes/secrets-store-csi-providers"
              name: providervol
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: HostToContainer
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/os: linux

```

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
csi-secrets-store/driver v1.3.0
csi-node-driver-registrar v2.6.2
livenessprobe  v2.8.0

- Kubernetes version: (use `kubectl version`):
1.23

**Additional context**
the strangest thing that deployment pod can run up success if I comment out the objectType: "secretsmanager" section

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-spc-k8s-secrets
spec:
  provider: aws
  parameters:
    # region: cn-north-1
    objects: |
      - objectName: "/kone/govplt/auroramysql/connectionstr"
        objectAlias: "db_conn_str"
        objectType: "ssmparameter"
#      - objectName: "/kone/govplt/elasticache/secret"
#        objectType: "secretsmanager"
#        jmesPath:
#          - path: endpoints
#            objectAlias: redis_endpoint
#          - path: port
#            objectAlias: redis_port

  secretObjects:
    - secretName: kone-govplt-secret # name of the Kubernetes Secret object
      type: Opaque # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
      labels:
        provider: "csi-driver"
      data:
        - objectName: db_conn_str
          key: db_conn_str
#        - objectName: redis_endpoint # name of the mounted content to sync. this could be the object name or the object alias
#          key: redis_endpoint # data field to populate
#        - objectName: redis_port
#          key: redis_port
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-k8s-secrets
  labels:
    app: nginx-k8s-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-k8s-secrets
  template:
    metadata:
      labels:
        app: nginx-k8s-secrets
    spec:
      serviceAccountName: govplt-deployment-sa
      containers:
      - name: nginx-deployment-k8s-secrets
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets"
            readOnly: true
        #   syncSecret.enable = true
        env:
          - name: DB_CONN_STR
            valueFrom:
              secretKeyRef:
                name: kone-govplt-secret
                key: db_conn_str
#          - name: REDIS_PORT
#            valueFrom:
#              secretKeyRef:
#                name: kone-govplt-secret
#                key: redis_port
#
#          - name: REDIS_ENDPOINT
#            valueFrom:
#              secretKeyRef:
#                name: kone-govplt-secret
#                key: redis_endpoint

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: nginx-deployment-spc-k8s-secrets
```

i am sure serviceAccountName: govplt-deployment-sa have secretsmanager permission

**Comment by eroseland** [comment] 2023-01-27 23:14
I am running into the same thing. Oddly enough, I can mount secrets cross-account just fine. However, trying to mount from secretsmanager within the same account and region is when I get that ***Failed to fetch secret from all regions*** error. I have tried both (I have excluded the region as well):
```yaml
spec:
  provider: aws
  region: us-east-1
  objects: |
    - objectName: "secret/name"
      objectType: secretsmanager
```
as well as the full ARN:
```yaml
spec:
  provider: aws
  region: us-east-1
  objects: |
    - objectName: "full secret ARN"
```

I am wondering if it isn't something with the csi-secrets-store-driver helm install for me because while I see the exact same errors you show in your logs, I also see this:

`E0127 21:53:25.935626       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"secrets\" in API group \"\" at the cluster scope\n"`

So perhaps the RBAC permissions or a ClusterRoleBinding is missing that is keeping it from creating the secret. I have confirmed in CloudTrail that the secret is getting accessed just fine. I am going to uninstall and reinstall the helm charts and see how it goes.

**Comment by mafeifan** [comment] 2023-01-28 08:35
@eroseland  any good news?

**Comment by eroseland** [comment] 2023-01-28 22:46
Yes, I did some further investigation on the secrets-store-csi-driver service account not having permissions and found this: https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/58
I added the flag to my install `--set syncSecret.enabled=true` and that seems to have done it. So apparently the sync is something that has to be enabled on install - must have missed that before.
Hope that helps!

**Comment by mafeifan** [comment] 2023-01-30 00:41
hmm, I have turned on syncSecret.enabled, and the issue still exist

**Comment by AdamStaudt** [comment] 2023-01-31 15:12
i was having the same issue as @mafeifan, and was able to narrow the issue down to the fact that one of my secrets, which stores key/value pairs in JSON format, had a quoted integer value for one of its keys. i also saw that the issue only manifests when attempting to use `jmesPath:` to access these keys directly, as mentioned above.

in particular, it will fail when trying to access a key which begins with an integer. if you comment only that key out under jmesPath, and retrieve other keys which don't begin with (or consist entirely of) numeric chars, it will work. also if i simply write the entire secret to a file in the container, it works, and writes the JSON content as expected. this shows that the issue doesn't have anything to do with IAM privs or even invalid JSON. i suspect this is just a bug in the way the jmesPath mechanism parses JSON keys in secrets.

unfortunately this may not solve the OPs problem, as it appears they are not using any keys which begin with integers, but based on their posts, it seems safe to say that the issue is contained within the jmesPath mechanism, and i would guess that there's something about one or more of your JSON keys that it doesn't like.

**Comment by remenaker** [comment] 2023-02-02 21:26
@mafeifan I ran into this same issue. I am not sure what I did to actually fix it, but I do believe in all the changes I was making the csi driver daemon set was not picking up on. I found that restarting every csi driver pod between each change made it work. Bottom line try restarting every csi driver pod when making any change to other resources.

**Comment by Soddi** [comment] 2023-02-02 22:22
Hi, I'm facing the same issue and I have also tried enabling sync secret (which really is an optional value and shouldn't be needed) can't seem to figure out why this happens. I've also restarted my node in which the CSI driver was deployed to.

Here's my error msg:

`failed to mount secrets store object content" err="rpc error: code = Unknown desc = Failed to fetch secret from all regions: secret_manager_metadata`

here's my SecretProviderClass:
```

 apiVersion: secrets-store.csi.x-k8s.io/v1
 kind: SecretProviderClass
 metadata:
   name: secrets-provider
 spec:
   provider: aws
   parameters:
     region: eu-north-1
     objects: |
       - objectName: secret_manager_metadata
         objectType: secretsmanager
         objectAlias: renovate_token
```

Does anyone know why i'm getting this error message and how to solve it?

**Comment by nitrocode** [comment] 2023-02-03 18:01
For us, we used a secret that contained a hyphen which needed to be quoted. The newer image seemed to be hiding the error message and saying "Failed to fetch secret from all regions" but the actual error was a failing jmespath query.

https://github.com/jmespath/jmespath.py/issues/109#issuecomment-346917804

```yaml
 apiVersion: secrets-store.csi.x-k8s.io/v1
 kind: SecretProviderClass
 metadata:
   name: secrets-provider
 spec:
   provider: aws
   parameters:
     region: us-east-1
     objects: |
      - objectName: "secret/api-key"
        objectType: secretsmanager
        jmesPath:
          - path: "\"api-key\""
            objectAlias: apiKey
```

Older image that showed the real error for us is the image `1.0.r2-6-gee95299-2022.04.14.21.07`. After we resolved it, we went back to the latest `1.0.r2-35` image.

https://gallery.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws

**Comment by Soddi** [comment] 2023-02-04 08:42
Having a hyphen in the secret was also the case for me and I tried creating another secret without any special characters but I still receive the same error. In reality, i'm generating the secrets and I really shouldn't be changing the secret value in any shape or form so it should handle all kind of secrets, including hyphens. Maybe this is a bug that needs to be fixed in a future version?

**Comment by mafeifan** [comment] 2023-02-04 13:15
@nitrocode  thanks, it can parse success now

I changed image version to `public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:1.0.r2-6-gee95299-2022.04.14.21.07`

my secret object in Amazon Secrets Manager is 
`{"endpoints":"gov-v2.kztygy.0001.cnn1.cache.amazonaws.com.cn","port":6379}`

it doesn't working when using the jemspath below

```
     - objectName: "/kone/govplt/elasticache/secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: endpoints
            objectAlias: redis_endpoint
          - path: port
            objectAlias: redis_port
```

but working when I add double quote

```
      - objectName: "/kone/govplt/elasticache/secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "endpoints"
            objectAlias: "redis_endpoint"
          - path: "port"
            objectAlias: "redis_port"
```


but parse port key failed, 

 `k describe pod nginx-deployment-k8s-secrets-76b77856c6-4bzbm`

the error is
`Warning  FailedMount  3s (x6 over 19s)  kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/nginx-deployment-k8s-secrets-76b77856c6-4bzbm, err: rpc error: code = Unknown desc = Invalid JMES search result type for path:"port". Only string is allowed.`


If i update object to  `{"endpoints":"gov-v2.kztygy.0001.cnn1.cache.amazonaws.com.cn","port":"6379"}`

it can parse success!

@Soddi ,  I agree, It's a bug,  I've tested it in other EKS cluster of the same version and it works without double quotes!

```
     - objectName: "/kone/govplt/elasticache/secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: endpoints
            objectAlias: redis_endpoint
          - path: port
            objectAlias: redis_port
```



hope it can fix ASAP.

**Comment by sandeep070** [comment] 2023-02-07 19:32
I had faced similar issue, my problem was with namespace with which I created a IRSA (IAM Role for Service Accounts) vs the namespace in which the pod is deployed into, they both should match, else we will end up with this error.

**Comment by istvan-fodor** [comment] 2023-02-07 22:39
I am getting the same issue, anyone else running into this? 
```
I0207 22:33:01.973821       1 server.go:124] Servicing mount request for pod env-secret-test in namespace recon-dev using service account recon-service-account-dev with region(s) us-west-2
I0207 22:33:02.055288       1 auth.go:123] Role ARN for recon-dev:recon-service-account-dev is arn:aws:iam::***************:role/recon-service-role-d9001c1
E0207 22:35:01.857556       1 server.go:151] Failure getting secret values from provider type secretsmanager: Failed to fetch secret from all regions: arn:aws:secretsmanager:us-west-2:***************:secret:recon-postgres-secret-e4c1f49-LsJb0h
```
I am using this image: `public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:1.0.r2-35-g41dc61e-2022.12.16.20.38`

**Comment by istvan-fodor** [comment] 2023-02-09 03:48
It turns out I had some networking issues. I also added the workaround by @mafeifan and it all works now.

**Comment by daithi-walker** [comment] 2023-02-10 22:37
@istvan-fodor what were your networking issues? We have a similar issue running the older driver version.

**Comment by istvan-fodor** [comment] 2023-02-11 00:49
@daithi-walker In our environment we were unable to access any AWS services without a proper Egress network policy. The secret store driver would not say anything about inability to reach the secret manager IP, etc, so it was pretty misleading. It would be pretty neat if we could set some verbosity level (as far as I can tell the helm chart doesn't support that) to see the root causes in the logs. 

Once I fixed that, I had to add to the permission policy of the assumed role `kms:Decrypt` and `kms:DescribeKey` on the encryption key used for the secret. As far as I can tell, the guides out there don't mention this, but I was getting decrypt errors (properly logged at least :) on the pod startup (on the pod with mounted secret that). Once I fixed that mount + env var started to work. 

I hope this helps.

**Comment by daithi-walker** [comment] 2023-02-11 01:24
Thanks for the additional info. 

Agree about logging verbosity. It's not overly helpful right now. I've run network traceability analyzer and can confirm the VPC endpoint in place for secret manager is allowing traffic from the default node out to the secret manager VPC endpoint so I dont think the issue for me is network on our side anymore. 

The newer version of the provider `public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:1.0.r2-35-g41dc61e-2022.12.16.20.38` is causing the "Failed to fetch secret from all regions" issue for us. But rolling back to the older version mentioned (`public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:1.0.r2-6-gee95299-2022.04.14.21.07`)  we get the post connection time out issue:

```
Warning  FailedMount  1s    kubelet            MountVolume.SetUp failed for volume "xxx-volume" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod <namespace>/<pod_name>, err: rpc error: code = Unknown desc = Failed fetching secret aws-access-key: WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post "https://sts.us-west-1.amazonaws.com/": dial tcp: lookup sts.us-west-1.amazonaws.com on [<ipv6-address>]:53: read udp [<ipv6-other-address>]:55269->[<ipv6-address>]:53: i/o timeout
```

We can roll back to an even older version of the driver and get it to work, but then we lose the ability to use `jmesPath` which is less desirable.

**Comment by Soddi** [comment] 2023-02-14 14:43
> I had faced similar issue, my problem was with namespace with which I created a IRSA (IAM Role for Service Accounts) vs the namespace in which the pod is deployed into, they both should match, else we will end up with this error.

Thank you, that was the case for me too! Once I matched the namespace/SA name, it started fetching the secrets as expected.

**Comment by arielazem** [comment] 2023-02-15 23:43
After getting `Failed to fetch secret from all regions` and not knowing the actual reason, I installed `1.0.r2-6-gee95299-2022.04.14.21.07` just as @nitrocode did, and that showed the actual error in the logs which was `WebIdentityErr: failed to retrieve credentials` and the reason was I missed to update the trust relationship between the IAM role used and service account - this is because I set it up manually not using the `eksctl create iamserviceaccount` command due to some limitations

The `Failed to fetch secret from all regions` error is very misleading and based on the messages here, there could be different reasons behind the scenes.

**Comment by andrew-llh** [comment] 2023-02-24 20:55
Same error `Failed to fetch secret from all regions` but it was due to the secret JSON having the value of `null` for one of the keys.  I also found the error misleading, but was glad I found this issue as it gave me the clue I needed.  :)

**Comment by mafeifan** [comment] 2023-03-05 14:32
well, finally i choose https://github.com/external-secrets/external-secrets solution.
it is more easy and less bug

**Comment by cold-logic** [comment] 2023-03-06 21:08
Yeah this is pretty fragile in it's current state. I was seeing the same error "Failed to fetch secret from all regions" until I compared the keys we were asking for in the manifest with the keys defined in our secret. If any keys are mismatched or missing it will fail with this error.

**Comment by vietvite** [comment] 2023-03-08 21:44
I had the same problem and fixed it, the reason was that I had set the trust policy incorrectly in the IAM role used to get the AWS secret manager.
If you follow [this aws guide](https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html) and set an incorrect namespace or service account name in the trust policy, you may need to update `"$oidc_provider:sub": "system:serviceaccount:$namespace:$service_account"` with the correct `$namespace` and `$service_account`
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::$account_id:oidc-provider/$oidc_provider"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "$oidc_provider:aud": "sts.amazonaws.com",
          "$oidc_provider:sub": "system:serviceaccount:$namespace:$service_account"
        }
      }
    }
  ]
}
```

Quick check your trust policy of your role using to get the AWS secrets
```bash
aws iam get-role --role-name IAM_ROLE_NAME --query Role.AssumeRolePolicyDocument
```

**Comment by tomaskovalcik** [comment] 2023-03-09 13:25
Please check your csi-secrets-store-provider-aws pods to see in more detail why it fails. It helped me to resolve my problem.

**Comment by jasonjlock** [comment] 2023-03-11 19:14
What work for us is the following: 
1. Upgrading from `0.2.0` to `0.3.1` outputs a better error message. The error is now `AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity` instead of `Failed to fetch secret from all regions`.
2. The IRSA trust policy's OIDC provider should include the cluster's ARN, e.g., `arn:aws:iam::xxx:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/xxx` instead of `oidc.eks.us-west-2.amazonaws.com/id/xxx`

**Comment by jbct** [comment] 2023-04-18 20:08
We have enhanced the log output with change https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/190/commits and believe this should help with the majority of issues in this thread. Please open a new issue if you continue to have any issues.

**Closed by jbct** 2023-04-18 20:08 UTC
Labels: triage/needs-investigation

**Comment by Manuv2u** [comment] 2024-09-01 09:21
@anyone..
I have restarted the CSI driver (Version 0.3.8 )and the AWS provider (version 1.4.5). What possible issues could arise?
