### ISSUE TITLE
Unable to retrieve Env set at the SecretProviderClass

### ISSUE THREAD

**Issue by brucedvgw** [aws/secrets-store-csi-driver-provider-aws#38] opened 2021-07-19 08:25 UTC
Hi I am able to create the SecretProviderClass and pull down a secret to the mounted volume, however every time I try to create the value as a Environment variable it fails.

I have been over and over the configuration and I can not spot what I am doing wrong. Is anyone able to help 🙏🏻 

Here is my secret-provider config.

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secret-application
spec:
  provider: aws
  secretObjects:
    - secretName: database-creds-csi 
      type: Opaque
      data:
      - objectName: database-creds
        key: password
  parameters:
    objects: |
      - objectName: "database-creds"
        objectType: "secretsmanager"
```

Here is my deployment yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: application
spec:
  serviceAccountName: db-secret-access
  containers:
    - name: application
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - "sleep"
        - "3600"
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-creds-csi
              key: password
      volumeMounts:
        - name: db-secret
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: db-secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws-secret-application"

```

I get the below error

```bash
Warning  Failed     5s (x3 over 7s)  kubelet            Error: secret "database-creds-csi" not found
```

However if I leave out the `env` section I can access the value if do this

```bash
kubectl exec -it application -- cat /mnt/secrets-store/database-creds; echo
{"password":"NEWPA$$WORD!!"}
```

Any help is appreciated. Thank you in advance.

**Comment by shapirov103** [comment] 2021-07-22 19:49
Same issue here, trying to use secret sync feature:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: argo-aws-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: bootstrap-repo-secret-sync
      type: Opaque
      labels:
        "argocd.argoproj.io/secret-type": "repository"
      data:
        - objectName: github-ssp-ssh   
          key: sshPrivateKey
        - objectName: github-ssp-ssh
          key: url 
  parameters:
    objects: | 
      - objectName: "github-ssp-ssh"
        objectType: "secretsmanager"
```
The behavior is exactly as described in the issue: env reference fails, however volume is mounted successfully when kubernetes secret is not referenced. Secret is not created. 
On EKS version 1.19:
    AWS provider image: `public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:1.0.r1-10-g1942553-2021.06.04.00.07-linux-amd64`
    CSI Driver image: `k8s.gcr.io/csi-secrets-store/driver:v0.0.23`

**Comment by emtammaru** [comment] 2021-07-26 14:54
Same issue here.  There appears to be an issue with `SecretsManagerSync` -- i.e. this test is not passing: https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/main/tests/aws.bats#L136

**Comment by mehowthe** [comment] 2021-07-26 17:56
I was facing same issue, for me this worked: https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/30#issuecomment-864118742

So probably you can try to install driver with these values:
```
helm upgrade --install csi-secrets-store \
--namespace kube-system secrets-store-csi-driver/secrets-store-csi-driver \
--set grpcSupportedProviders="aws" --set syncSecret.enabled="true"
```

**Comment by shapirov103** [comment] 2021-07-26 19:15
@mehowthe thank you and confirmed, the issue was due to the helm chart value for sync secret was not set. Did not expect the behavior to be "opt-in", however, it is marked as optional, so works as designed.

**Comment by emtammaru** [comment] 2021-07-26 22:26
Thanks @shapirov103  and @mehowthe that was in fact the issue for me as well.  Note, the secret only "syncs" with k8s secrets after applying the pod/deployment/etc that references it with `secretKeyRef`. I was confused at first why it wasn't showing up in `kubectl get secrets` after applying the `SecretProviderClass` by itself.

**Comment by brucedvgw** [comment] 2021-07-27 01:55
Adding `--set grpcSupportedProviders="aws" --set syncSecret.enabled="true"`  works a treat. It creates the Environment Variable.
However once the secret value is rotated in AWS Secrets Manager, only the file is updated and not the Environment value.

**Comment by askulkarni2** [comment] 2021-08-13 05:08
Leaving `syncSecret.enabled = false` is considered a best practice as per the [docs](https://secrets-store-csi-driver.sigs.k8s.io/topics/best-practices.html).

**Comment by simonmarty** [comment] 2022-04-21 19:20
This is indented behavior of the Secret Store Driver, closing.

**Closed by simonmarty** 2022-04-21 19:20 UTC
Labels: wontfix
